FROM ubuntu:22.04

RUN apt-get update

RUN apt-get install -y build-essential curl git cmake libclang-dev iproute2 iputils-ping

RUN curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly -y
ENV PATH="/root/.cargo/bin:${PATH}"

COPY pause.c /pause.c
RUN gcc -o /pause /pause.c && rm /pause.c

COPY client /client
WORKDIR /client
RUN cargo build --release

CMD ["/pause"]